after-login-command = []
after-startup-command = []
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Disable cmd-h
automatically-unhide-macos-hidden-apps = true

accordion-padding = 20
default-root-container-layout = 'tiles' # tiles|accordion
default-root-container-orientation = 'auto' # horizontal|vertical|auto

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

    # See: https://github.com/2KAbhishek/mac2k/blob/b9345a21917e5af691bfb21e8b87766517ec9fc5/config/aerospace/aerospace.toml#L102
    alt-enter = 'exec-and-forget open -n /Applications/Alacritty.app --args -e tmux new-session -As home'
    alt-shift-enter = 'exec-and-forget open -n /Applications/Alacritty.app'

    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion'
    alt-w = 'layout h_accordion' 
    alt-e = 'layout tiles horizontal vertical'

    alt-shift-space = 'layout floating tiling' 

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'
    
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# See: https://github.com/nikitabobko/AeroSpace/issues/246
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = "md.obsidian"
run = "move-node-to-workspace 5"

# TODO
# [workspace-to-monitor-force-assignment]
#     1 = '^built-in retina display$'
#     2 = '^built-in retina display$'
#     3 = '^Dell$'
#     4 = '^Dell$'

# Sources:
# - https://nikitabobko.github.io/AeroSpace/goodies#i3-like-config
# - https://nikitabobko.github.io/AeroSpace/guide#default-config
# - https://github.com/andrew8088/dotfiles/blob/0e3f791df6513cdcb4b54d35d0db72e555d59d57/aerospace/aerospace.toml
# - https://github.com/2KAbhishek/mac2k/blob/main/config/aerospace/aerospace.toml
