[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

# [font.bold.italic]
# family = "DejaVuSansM Nerd Font Mono"
# style = "Bold Oblique"

# [font.italic]
# family = "DejaVuSansM Nerd Font Mono"
# style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 2048
multiplier = 8

[window]
opacity = 0.98
decorations = "None"
decorations_theme_variant = "Dark"
title = "Alacritty"
padding = {x = 6, y = 6}

# [window.class]
# class = "Alacritty"
# instance = "Alacritty"

[general]
live_config_reload = true
import = [
    # "~/.config/alacritty/themes/rose-pine/dist/rose-pine.toml",
    "~/.config/alacritty/themes/iron-neon.toml",
]
